### ISSUE TITLE
新北市手機簡訊報案號碼需要更新

### ISSUE THREAD

**Issue by alecchen** [mlouielu/smspolicetaiwan#1]
2022/3/28後新北市的報案電話改成0911-510-105，原本的0912-095-110號碼在5/1之後會失效，請參考[此公告](https://www.xinzhuang.ntpc.gov.tw/home.jsp?id=a6af86d2ea26b816&act=be4f48068b2b0031&dataserno=436130a17f4f9f13cab2c33ee3394b5f)，以及[內政部警政署網站資訊](https://www.npa.gov.tw/ch/app/artwebsite/view?module=artwebsite&id=808&serno=d08673f4-0775-4a09-b4d8-d47c2c4edca2)，謝謝。

**Comment by mlouielu** [comment]
Thanks, fixed in 227a6e9.
